# Generated by Django 5.2.1 on 2025-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='qualifications',
        ),
        migrations.AlterField(
            model_name='job',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
