# Generated by Django 6.0.4 on 2026-04-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='photo',
        ),
    ]
